### PR TITLE
Fix misleading error on bad PostgreSQL connection string

### LINKED ISSUE #3379: outbound-pg: Wrong error on malformed connection string
The first place that `connection.open` can fail is when checking the host against `allowed_outbound_hosts`: https://github.com/spinframework/spin/blob/a12c2bf7fc85e538254e04f5a36ac01975061ed2/crates/factor-outbound-pg/src/host.rs#L85-L93

This `is_allowed_address` function attempts to parse the connection string and on parse failure returns `Ok(false)`: https://github.com/spinframework/spin/blob/a12c2bf7fc85e538254e04f5a36ac01975061ed2/crates/factor-outbound-pg/src/host.rs#L42-L44

...which then gets translated into a `ConnectionFailed("address {address} is not permitted")` error, which is wrong.

I'm not sure why `is_allowed_address` returns `Ok(false)` on parse error; it should probably either propagate the parse error or - if there is reason not to leak those details - turn it into a fixed e.g. `"invalid connection string"`.

### PR DESCRIPTION
**Pull request by itowlson**
Fixes #3379.

Bad connection string: `Error::ConnectionFailed("invalid connection string: unknown option 'honk'")`

Denied host: `Error::ConnectionFailed("address pantoufles.com is not permitted")`

### CODE REVIEW

File: crates/factor-outbound-pg/src/host.rs [hunk 1]
```diff
@@ -55,15 +64,22 @@ impl<CF: ClientFactory> InstanceState<CF> {
                             .or_else(|| if ports.len() == 1 { ports.get(1) } else { None });
```
Comment (lann) [inline crates/factor-outbound-pg/src/host.rs:64]: Completely unrelated to this pr but since I'm here and on my phone: surely this is a bug?

**Comment by itowlson** [comment]
This might have fixed at least one occurrence of #3380 as well.

File: crates/factor-outbound-pg/src/host.rs (hunk 1 above)
Comment (itowlson) [reply crates/factor-outbound-pg/src/host.rs:64]: Could you elaborate on which bit is wrong?

Comment (lann) [reply crates/factor-outbound-pg/src/host.rs:64]: `if ports.len() == 1 { ports.get(1) }`

Unless I'm badly confused this would always return `None`. Ought to be `.get(0)` or better `.first()`.
